/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package factorialcalculator;
import java.util.*;
/**
 *
 * @author Lab6 - PC17
 */
public class FactorialCalculator {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        Scanner scn = new Scanner(System.in);
        
        
        
        for (int rep = 1; rep <= 5; rep++) {
            System.out.println("Enter a positive integer: ");
            int num = scn.nextInt();
            
            if (num < 0) {
                System.out.println("ooooooooooooooooooooooooollloooooooolllllolloooooollllllooloolloolllodollloooooooolllllloolccllolloooooooooooooolllllolcloloollllollloloolllllodooooooooooloooolcllloooooolllloollllooolllooooooollllllllloooooooooolooooolllodoollloooooolllcllllllooooooolloooollllldoollolllllloooooooooooooooooooooooooo\n" +
"ooooooooooooooooloolcc::::::clc:::::::ll:::::::clllc:;;:ccc::cloolllllc:;;;;;;;;:clolloolllllcc:::::::cllc:::::::::clllc:::c::::clloolllolloolc::::::::::::;:cccllloolc::::::::ccllloolc:::;,,;;;:cccc:::::::::::::c:::::cllccc:;,,;;:clollllllc::;,;;;;;:ccllc:::::::cc::::::::::;::::clooooooooooooooooooo\n" +
"ooooooooooooooooolol;.';:::,....,:::;'...,::::'.,c:,',:::::,';coool:,''';:cllc:,'.,:clllooooo:'.;:::;,',;'',:cc:;'.'cl:'.;:::::,.,clllooooooo:..;::::::::::::;'.,:lllc'.;::;::,';cllol:,.':cccccc:,','.,:::::::ccc:c:;:;..,,'';:cllc:,,',;coo:,'';:cccc:;'.';,.':ccc:'.';::::'..;::::,';looooooooooooooooooo\n" +
"oooooooolooooolloool,.c0NXXO:..cOXNNKo. 'xXNN0:.,:,.cOXXXXXOc.,clc;',lk0XNNWNNNXOd:'.;lllolll:.,kXNN0l...;d0NNXKd,.,cc,.:0NNNNXk;.'cloollllol;.,kXNNNNXNNNXXXXOl'';lc''l0XXNNXk;.;cc:,':dOKNNNNNNKko;..lKXXXNNXNNNNNNXXO,..:x0XXNWWNXX0kl;',,.'o0XNNNNNNX0xc' .c0NNXk,.;ONNXO:.,kXNN0l.'cooooooooooooooooooo\n" +
"ooooooooloooolllloll:.'xNWWXd.'xXWWMWO,.cKWWNk,.;'.;kNWWWWMNx,.;c,.:kXWWXKOkxOKWMWKo'.;clllol;.;0WMMXo..l0NWWXOl,';cc;.;kNWWWWWNx'.;oollooool:.;OWWWN0kxddOXNWWXo.':,.:0WWWWWWNx,.;:,.c0WWWXkddkKNNNx,.cO00KXNWWWWX0000d,,dKWWNX0kkOKWWWXk;..;kNWWNOdodOXNN0c..;0WWNx. ,OWMWO, .xNWW0:.;looolloooooooooooooo\n" +
"ooooooooooolllllllllc'.lKMWNO::OWWWMWKc,dXMMKl.';''dXWN00XWWKo'.'.,xNWWXd,.. .;oOOOd;.,clllol;.;0WMWXxlxXWWNOl'.;cll;.'kNWNK0XWWKo',:lloloool:.,OWMWKo:,.':kNWWKl..,.'xNNNKOXWWKl.';'.dXNWWXxc;:clll;..',,''cOWMWXo'','.'dNWWW0c'.'':kNWWNx'.:0WWWNOl:;cllc:'. ,OWMXl. .xWMNx' .oXWWO,.:looooooooooooooooooo\n" +
"ooooooooooollllllllll;.,kNWWXxkNWXKXWWOdKNWNk;','.cKWWKl:kNMWKl. .:0MMW0;  ':cclddoc'.'cloolc;.;0WWWWXXWMWWXd'.,looc..oXWW0l:kNWW0c.,loollooo:.,OWWWNXK0O0KNWWKo..,,'lKWWKl;kNWNO;.',.;OXWWWWNXK0Oxl,..;cc,.,kNMMKc.'c,.;OWWWXd'':c'.lXWWWK:..l0NWWWWNXK0xl:.  .dNMK:. .oXWXo. .:0MNx..coooooooooooooooooooo\n" +
"ooooooooooooollloolooc'.lKWMWXXWNkoONMNNWWWKl....;OWWN0:'oXWWW0: .cKWWW0; .l0NNNWWWKl..clollc;.;0WWWWMWWWWMWXo'.;lc,.:0WMWO;'oXWMWk,.;loolloo:.,0WWWNK0OkO0XWWXx;...cKWWNk;'oXWMNk,....'cxO0KXNNWWWNOc.'cl;.'kNMMKc.,l:.;kWMWNo.'::'.lXWWWK:  .;oxOKXXNWWWWXd' .lKNO;...cOX0c...,kN0c..clooooooooooooooooooo\n" +
"ooooooooooooooooooolol;.:OWMWWWWKl,oXWMWWWWk;...,xNMMWN0OKWWWWXx' ,OWWWNx,.':lkXWMWKl.'loolll;.;0WMWWXOddKWWWNx;.,'.;kNMMWX0OKNWMWXd..:lolloo:.,OWWWKo:,..;xNMWNk'.,kNMMWX00KWWWWXd'..:ddxdc,';o0NWWNo..:l;.,kNMMKc.,cc''dNMWWO:..'';xXWMNx,.;odddl:,;oONWMW0:..:ddl'...,ldl,...,lxo;..:looooooooooooooooooo\n" +
"llllllllllooooooooolooc,'oNWWWWNk, ,OWMWNWXo'..'dXWWWNXXXXXNWWWKl..c0NWWNKkxdx0NWWWKc..loolll;.;0WWWNd'..:ONWWNk;..'dXWWWNXXXXXNWMWKl.'cooooo:.,OWMWNK0OkkkKNWWNk,.dNMMWNXXXXXNWWWKl..oXWWN0dookXNWWKc.,cl;.,kNWWKc.,cc;';xXWWNKkxxkKNWWNk;..cONWWXkdoxKNWMNx'.,kKK0l. 'd0XKd. .o0KKk;.;looooooooooooooooooo\n" +
"lllllllllloooooooollool;.;ONWNNKo. .oKWNNNk;...:OXNN0l;;:;;oKNNNO;..;oOXNNWWWWX0O0N0c.'lollll;.;ONNWKl..,.,xXNNXk:'c0NWNkc;:;,;o0NNNO;.;loooo:.,kNWWNWWWWWNNWN0x;'c0NNXOc;;,,;oKNNXk;.'lkKXNWWWWWNKkc''coo;.,xXWW0:.'cll;..:x0XNNWWWWNKkl,',,';d0XNWWWWWWXOo'  ;ONNXo. ,kNWNk' .dKNNO;.;looooooooooooooooooo\n" +
"lllllllooollloooollloloc'.;:ccc:'...':lcc:,....,cccc,.';:,.';cccc,..'',;:clllc:,.'::..,lollll:..;ccl:,.;c;.'::ccc;',:lc:,.'::,.':cclc'.,cooooc..:ccccclcccccc:;'..,ccc:,.';;,..:ccc:'..'',:cllllc:,,,;clol:'.,clc;..;lollc;'',;cllllc:,'',cll;'',:ccllllc;,,,'..;llc,...,ccc;. .,:cc:.':looooooooooooooooooo\n" +
"oooooooolllllllloolllllol:;;:::::clc;;;;;;:ccc:;;;;;;:loolc::;;;;;;clc:;,,;;;;;::;;;;:cooololl:;;;;;;::clc:;;;;;::;;;;;;;:clllc:::::;;:cllllll:;;;;;;;;;;;;;;;;::;;,,;;:cclll:;;;;;;;;:c:::;;,;;;;;clllllccc:;;;,,;:llloolllc:;;;,,;;;;:lllloolc::;;;;;;;;:cllc;;;::::::;;;;;;::;;;;::looooooooooooooooooooo\n" +
"ooooooooooooooooooooooooooollloooolllooodddoollllooollooolllooollllllllllooooollloolllloollllllloooolloollllllllllllllloollllllllllllcllllclllllllllllllllllllclllclloollllllccccllllollcllllllllllllllllllllllcllllclooooooollllllloolllllllollloooollllloooolllloollollllooollllooooollooooooooooooooooooo\n" +
"oooooooooooooooooooooooooooolooooooollooooooollllooollooooollloollllllllooolooolllllllllllloollllooooooolooooolllllolllooooooolooolllccclllloolllllllccclllooolllllllcccccccccccccccloollccccllcclolcclcllllllllloolllollllooolllllllooollooollllloooollllllooooooolooolllooollloooolllllloooooooooooooooooo\n" +
"ooooooooooooooooooooooooooloddooooloooolloooooolloolllloooolllloooloooolllllooolllllloollloolooooooooooooooolllloooooollllllllloollllllllllllllllllllccclllooool:::;,,'''''''''',,,,;cclllllllllllllllllcccclllloolllooooloolllooooooooolooooolooooooooolllllooolllooooolloollloooooooollllooooooooooooooooo\n" +
"ooooooooooooooooooooooooooooooooooooooollooooooolllolllllllllllloooooooolllooooooooooooooooolooooooooolooolloollooooooollloolllllllllllllllllllccccccllllllcc:;'...                 ...';:cllllllllllllllccclllllooooooooooooooooolooolllloooooooooooloooooolloooollloooolooollooooooooooooooooooooooooooooo\n" +
"ooooooooooooooooooooooooooooooooooooooolloooooooooooooooolllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllllc;'...                          .',;:cllccccccllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"oooooooooooooooooooooooooooooooooooooooolooooooooooooooooollloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllollcc;'.                                ...,:cllllllllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllooc;,'.                                     ..,;:clllllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"oooooooooooooooooooooooooooooooooooooolooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllcllc,..                    .....                ..';cllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"ooooooooooddddoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllolllllllllll:,.                    ....''.......            ..;clllllclllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"dddddddddddddddddddooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllollllollllllllllc;.                    ..';:cccc::;,'....         ..,:cllllcclllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"xxxxxxxxxxdddddddddddddddooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllloooolllllc;'.                  ...',:clooooollc:;,,'.......  .';:cllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"xxxxxxxxxxxxxxxxxddddddddddoooooooooooooooooooooollooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllloolllllc;'.          ..     ....',:cloodoooodddooolc:;,'''...';:cllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"xxxxxxxxxxxxxxxxxxxxxxdddddoooooooooooooooooooolllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllclll:,. ....................',;:loddddddddxxxxxxxdoooooolcccclllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"kkkkkkkkkkkkkkkkkxxxxxxxdddddoooddoooooooooooollllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllllllc;......................',;:loddddddddddxxxkkkkkkOO0K0Okxolllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"kkkkkkkkkkkkkkkkkkkkxxxxxxxddddddddddddooooooollllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooloolllllllllllllllllllllllllcc:'.',;;''....'''''''''',;:cloddddxddddddxxkkOO00O00KXXXK0xolllcllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"OOOOOOOOOOOkkkkkkkkkxxxxxxxxxdddddddddddoooooooooooooooooolllloooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllllllcc:;'.;coc;;,,,,,,,,,,,,,,;:lloddxxxdddxxxxkOOO000KKKKKXNNNKkdlllcclloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"000000000OOOOOOkkkkkkkkkkkkxxxxddddddddddoooooooooooooollllllloooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllccccccccclllcllcc:;cll:,,,,,;;;;;:cc::::cccclodddddxxkkkO00KKKKKXXXXXNNNXOdlllcclloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"KKKKKKKKKK0000OOOOkkkkkkkkkkkxxxddddddddddooooooooooolllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooolllllcllllllllllllllllccclllloooc;,''',;:::loddolclllc;,,;clodxkkkkOO0KKXKXXNNWWWWWXOollllccllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"KKKKKKKKKKKK000000OOOOOOOkkkkxxxxxxdddddddooooooooooooolllllllooooooooooooooooooooooooooooooooooooooooooooooooolllllllllclllllllllllllllllllloooddxdoc:;;;::cldxxdooodkkdc'..',;clodxkO00KKKKXNNNWMMMWXkoloolccllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"KKKKKKKKKKKKKKKKK00000OOOOkkkkxxxxxxddddddddoooooooooolloollllloooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllllooooddolodxdlc:,,;codkkkxxk0KXKkl,........,:ldkO0KKXXNXNWWMWWKkollollcloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"XXXXXXXXXXXXXXXXXKKK0000OOOOkkkxxxxxdddddddddooooooooolooolllllooooooooooooooooooooooooooooooooooooooooolooooolllllllllllllllllllllcllllooddool:;:cllc::,,:oxkkkxxOKXX0ko:,..........',:cdk0KXXXXWWWWN0xlllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"NNNNNNNNNNXXXXXXXKKKKK0000OOOOkkkkxxxddddddddddoooooooooooooolloooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllcclcccllllloool:,..,:llc::;;cdkOkxxOKKOdl:;;;;,,''........';lxkOkkOXWMWNKxoolllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"NNNNNNNNNNNNNXXXXXKKKKKK000OOOOkkkkxxdddddddddddooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllccllool:,.';looolc::ldkxdddxxl;,,;:cc::c:,'.......';cloolcokXWWNXOxdollllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"NNNNNNNNNNNNNNNNXXXXXKKK00000OOOkkxxxxdddddddddoooooooooooooooooooooooooooooooooooooooooollllooooooooooooooooooollllllllllllllllllllllcclloodoc::clloooollodxxddddc'..,:clc:cllc,.......',:cllc:lkKNNWN0kdollllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"NNNNNNNNNNNNNNNNNNXXXXKKKK000OOOkkkkkxxxddddddoooooooolllloooooooooooooooooooooooooooooooollllooooooollllllllllllllllllllllllllllllolllllllldddolc:lodddddxkkkkkkxc'..,:loodxkxo:'.......';clolclx0KXXKOxolllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"NNNNNNNNNNNNNNNNNNNXXXKKKKK000OOOkkkkkxxxxdddoooooooooolllloooooooooooooooooooollooooooooolllooolllllllllllllllllllllllllllllllolllllllllllodxdlc::ldxkxxkkkOkkkOko:'...,;:codxo:,.......',:oddlcldxkOkxollllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollll\n" +
"WWWWWWWWWWWWWWWWNNNNXXXKKKKK0000OOkkkkxxxxddddoooooooooolllooooooooooooooooollllllllllllllllooooooooooollllllllllllllllllllllllolllllllllooxkOkdolloxxkkkkOOOOkkkkdl,......';cll;'.....''',;lxkxolcloddoollllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollll\n" +
"WWWWWWWWWWWNNWWWNNNNNXXKKKKK00000OOOkkxxxxxdddoooooooooolllllllooooooooooooolllllllllllllllllllllllllllllllllllllllllllllllccllolllllcllloxO0K0OkxkkOkkxkkOO0OOkOkxdc;'....',::;'.....';;;;;cdO0Oxoclllolllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolloooooooooollllllllll\n" +
"WWWWWWWWWNNNNNNNNNNNNXXXKKKKK00000OOkkxxxxxdddddoooooooolllllllooooooooooooollllllllllllllllllllllllllllllcclllllllllllllllllllllllllllllok0KKOOOO00OkxdxxkOOkkkOOOOkxoolllcllc:,'.',;coddolldO00kdolllllllllllcloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllloooooooollloooollll\n" +
"WWWWWWWWWNNNNNNNNNNNNXXXXKKKK00000OOOkkxxxddddddooooooollllllllloooooooooooollllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldOKKKOkOO00OkxxxxxxkxkkOOO00OOO0000OkxlccoddxkO0Okxdk0KK0kdolclllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllloooooooollloooollll\n" +
"WWWWWWWWWWNNNNNNNNNNXXXXXXKKK00000OOOkxxxxdddddddoooooollloooolllllllllooooolllllllllllllllccclllllooooodddxxdddoollllllcccllllllllclc::cd0K0OxxxO00OkxxddxxxxxkOOO00000KKK00OxolodxkOKXXK0OxOKXX0xollllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllloooooooooolllllllll\n" +
"WWWWWWWWWWWNNNNNNNNNXXXXXXKKK00000OOOkxxxxxddddddoooooolloooooollllllllooooolllllllllllllllc:cloollloooodxxxdollc;,'''''',,;cloooolllc;,:d0KOxdddO00kxxxdddxdddxkkOO00KKK0OkkkxdoolloxKNNNNX00000kdollllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllooooooooollllllllll\n" +
"WWWWWWWWWWWWNNNNNNNNXXXXXXKKK00000OOOkkxxxxdddddddoooooloooooooolllllllooollllllllllllllllllooddolccllcccc:;,..............';codddlcc:,,cxOOkxdddkOkxxxxdddxxdxxkkOO0K0OkdooddoollloxO0XXXXXXKkdddolllllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllooooooooollllllllll\n" +
"MMMMWWWWWWWWWWNNNNNXXXXXXXKKK00000OOOkkxxxxdddddddddoooloooooooollllllllllllllllllllllllloodxxkxollodoc;,'.............',;::codxkxo:;;,;lxkkxxxddkkxxdddddxxxxdxxkkO00Oxoodxxddddddxxk00000KKOdllllllcclllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllloooooooooollloooooo\n" +
"MMWWWWWWWWWWWWWNNNXXNNNXXKKK00000OOOOkxxxxxdddddddoooolllooolllllllllllooollllllllllllllooddolccccllllc::,'.''........',:lddxxxxxdl;;;,;lxkxxddddxkxdddddddxxxxxxkkOOOkxdxk00OkkOOOOkkO0KXK0Odolllccllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllooooooooooolllloooo\n" +
"MMMMWWWWWWWWWWWNNNNNNNNXXXKKK0000OOOOkkkxxxxxddddddooolllooolllollllllloooollllllllooooooolc:;,,,::clodxoc,',,,'.'',;::lodxkxdoc::;;;;,,:lddooooddxddooooodxxxxxxkkOOkxddxk0KXXKKKKK0kkOKXKOdlcccccclllcccllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllooooooollllloooo\n" +
"MMMMWWWWWWWWWWWNNNNNNNNXXXXXKKKKK00OOkkkxxxxxxddddddoollloooolooollllllllllllllllloooddolc:;,,;;:coxOKK0ko:;:::::::::cclllllc:,...',;;'.';clllllloooolllllodxxxxxxxkxxdooooxkkxxxxxkxxkOOOxdlccclllllllcclllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllooooooollllllooo\n" +
"MMMMWWWWWWWWWWWWWWNNNNNNNNNNNNNNXXK0Okkxxxdddddddoooooolloooolooollllllllllllloolllodxxdc;,,,;:oxOKXNXXX0xlc:;;;;;;;;;;,,'.........,;,...',:cc::cccclllcccloddddoodxxdolcc::llc;'.':ok00kdolllllllllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllooooooollllllooo\n" +
"MMMMWWWWWWWWWWWWWWWWWWWWNWWWWWWWWNXK0Okxxdddddoooooooollloooolooollllllllllloollllodk00Od:,,:lxOKXXXXXXKK0ko:'''...................,;'.  ..',;;::;;:cccclcccloolllodkkxdol:,;ldl,..:dOOkdoolllllllllllloolllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllooooooollllllllo\n" +
"MMMMWWWWWWWWWWNNNNNNNNWWWWWWWWWWWWNXK0OOkkxxdddddddoollllllloollooooooooooooolllloxkKXNKxc::ok00OkkO0KXXXK0kl,.....................,'.     ..',;;;,;:ccccccccllllloxkOkkOOkddkOkdooxOkxolllllllllclllllllllllllllollllooooolllllllllllllooooooooooooooooooooooooooooooooooooooooooooooooollllooooooooooooooo\n" +
"WWWWWWWWWWWWWWNNNWWWNNNNNNNNNWWWWWWNNXXXXXK0OOkkxxddollloooooollloooollllloollclldOKXKOdlloxkkxo:::loxOKXXKOko;'...       ............     ...',,,'',,,,;:cccclloooxkkkxk0KKKXK0OOOkxdollllllllllcccllllllllllllllllloollllllllllllllllllooooollooooooooooooooooooooooooooolllooooooooooollllllllooollllllll\n" +
"WWWWWWWWWWWWWWWNNNWWWNNNNXXXXNWWMMMMWWWWMWWNNXK0OOkxxdoooooooooloooolllllllollllox0XXKkook00ko:'....';oxOKKKK0xc'......       ..........................',;;::cloddxkkxxxkkOO000K0koc;;:ccclllooolllllllllllllllllllllllloooooooooolllllloooolllloooooooooooooooooooooooollllllllllllllllllllllllooollllllll\n" +
"NNNNWWWWWWWWWNNNNNNNWWWNNNXXNNWWWMMMWWWMMMMMWWWWNXKK0OOxdolllollooooollllllllloodxkkOOOkO00xc,..     .';lxOKXNXOd:,............    ..........       ....,,''';:cldxkkkxddoooxO000xl'...',;:::ccllllllllllllllllollllllllloolllllllllllllloooollllooooooooooooooooooooolllllllllllllllllllllllllllooooooooooo\n" +
"NNNNNNWWWWWNNNNNNXNNNNWWWWWWWWWWWMMWWWWWMMMMMMMMMWWWWNXK0kdlllllloolllllllllllllloodOKNXKOd:'.         ..;lxOKXXKOdc;''',:clc:;'.....'...            .........',:loxxxxxxxdxk00Od:'.  ......'',;;;;::::cc:::::cccclloooolllllllllllllllllloooollloooooooooooooooooooollllllllllllllllllllllllllolloooooooooo\n" +
"KKXXXXNNNNNXXXXXXKKKXNWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWX0xoolllllllllccllolllc:;;:oOXNX0d:'.  .......   .':ok0XXXKOdl:;:codxxdddl:'','....                   ..';:looddxxxkOOxc,.    ...   ..',;;:::;;;;;;,,,,,,;:cloollccllllolccccllllllloooooooooooooooooooooooolllllllllllllllllllllllllllloloooooooooo\n" +
"0000000KKKK0000OkkxkOKXNNNWWWWWWWWWWWWNXKK00KKKXNNWWWWWWWXOxdoolllcccllllolc:;,'..'cx00Oo;.. ..,;;;,''.....';lxOKXNNX0kocccllooddoc;,,,....                      ..,:clloooll:,..   ......     ...',;;;;;;;;;;,,''''',;clllllllllclllcccllllloooooooooooooooooooooollllllloolllllllllllllllllllooooooooooooo\n" +
"K00OOOOOOOkkkxxxdooodx0XNWWNXKKXXNWWWWXK0OxddxxkO0KXNWWWWNK0Oxdollllllllllc:;;,'..';cooc,.  ..,::;;;;;,,''',;:oxO0XNWNX0kdlcccccc:;,,;,,'...                       ...'''''...     .,:cc:,..     ...'''',,,;;;,,,''....':lddolcccllollllllllllllloooooooooooooooooollllllllolllllllllloollllllloooollooooddd\n" +
"00000OOkkkxxdddoollcclx0XWWX0kddxkOKNNNNKOxolcclodxOKXNWWWWNK0kxdoooolllc:::;;;,'....''.....',,,,,;;::::ccccccldxk0KXNNNNKOxddddolc:;,'''''...                ..........   ......,:ldkO0Od:.     ......'''',,,'''','.....,codoollllolllllllllllllllloooooooooooolloolllllllllllllllllllolllloooooooollooodoo\n" +
"00000OOkkkxdollllllccldkKNWNKxoccclxOXWWNKkoc;,,;;:cok0XNNWWWNXK0OOkkkxdc:::ccc:,.....'.',,;,;;;;::::ccllooooddxkOO0KXXNWWNK0OOkkdoc:,'...............   ......'''......'',;:clodxxkOO0XX0o,.    ............''''''.......';ldddlllllllllllllllllllooooooooooooooooolllllllllllllllllllooolloooooooooooooooo\n" +
"OOOOOOOOOkxdlccc::::;::ldOKXX0OxddxkO0XNWNX0kdolc:;'';coxOKXNWWWWNNNNXKOxoodxxxoc;,',;:cclc:;,,,;::::cclooddxkkOOO00KKKXNNWNXK00kxolc;,,''''',;:clllllllloooooolllccllllodxkkkxxdolcclx0XKkc'.  ................'''.........;lddolllollllllllllllllloooooooooooollllllcccllllllllllllllooolloooooooooooooooo\n" +
"kkkkkkkkkkkxdolc:;,''',,;coxkkkxolllloxOKXNWNNXXK0kdl:,',;cdkKXNWWWWWWWNKKKXXNXKOxoooddoc;,,,,,,;::cccloodxxkOO000KKXXXXXNWWNXX0OkxdoooddoddddxkO000KKKKKXXXXK00OOOOOkxxddolc:;,,'..',cx0K0xc'.  .','... .... ........''''...;ldxdollllllllllllllllllllllllooollllllccclllllllllllllllloooooooooollooooooooo\n" +
"kxxxxxkkkkkkkxdlc;,''..'',;:cllc;'....,codxk0KKXXNNNXOdc;,;:ldk0000KKXNWWWWWNNNWNK0OOxl:,...',,;::cclodxxkkO0KKKXXXNNNNNNNWWWNXK0OkkkO00OkxxdoodxkOO0K00O000OOkkkxddoc:;;,''..........;okKX0xc,...,;;'..       .......,,,''...,cdxdoolllllllllllllllllllllllllllllllllllllloolllloollllooooooooooooooooooooo\n" +
"xxxxxxxxxxkxxxddoc:,'....'..,;;;,'..........,;clox0XXXK0OkxdddxxxdoodkKXWWWNKKXWWWNX0o,.....,;::::coxk000KKXNNNWWWWWWWWWWWWWWNXXK0OOO0K0Oxdolc::cloodooolcllccccc:;,..................,cxKXX0xl;'....................';:;,.....':oddollccllllllllllllllllllllllllllllooolllooolllllllllllllllloooooooooooooo\n" +
"ddxxxxxxdxxddddddolc:;,'......',,'....     .....',:lxOKXXXXXXXXXXKOxxkKXKK0OO0XWWWWNOl'....,::::::lxOKXNNNNWWWWWWWWWWWMMWWWWWWWWNK000000kxdolc;;;;;;:;;,,''..',;;;,'..................':d0XXX0Oxo:;,'''',''....     .,:c;'......,:oolllcclloolllllloooolllllllllllllooollclloolclllllllllllllllooooooooooooo\n" +
"oddddddddddddddooooool:,'..............     ........';ldkOKXNNNXNXXXXNNKOxoookXWWWNXOo;....,;::::coOKNNWWWWWWWWWWWWMMMMMMWWWWWWWNXKKXKK0Okxdoc:;;,'',,,,''.....'''....................':oOKXXKK0OOkxxxxxxxdol:;,''',;cll:;''''..',:lllccclloollcllloooolllllllllllloodoolllllllllloolllllllllclooodooodooooo\n" +
"oooooooooooooooooooddolc:,'............       ...    ...':lxOKKK000KXX0kdolodOXWWWWNKkl;'.',;;::cox0XNWWWWWWMMMMMMMMMMMMMMMMWWWWNNNNNNNXKOkdoc::;;,,;;;:;,,'...........................,cx0KXXKKKKKKKKKKKXXXKK0OOkxxxkkkdoc:,,,'',:loolllllolllllllllolllllllllllllodddddoooollllloolllloollcclloooolodddddx\n" +
"ooooooooooooooooooooooollc:;'..........                ...,:ldO00OxxxddolcclokXWWWWWNKkoc;;;:::cldk0XNNWWWWWMMMMMMMMMMMMMMMMMMMMWWWWWWWWX0kxdollccc:::::;,'''..........................'cd0KXXXXXXXXXXXXXXXNNNWWNXXKKXXXXX0kxddoodxkkkxdooollllllllllllooooolloollllooddxxxxdoolloddollloollllloooooodxkkO00\n" +
"ooooooooooooloollllllloooollc:;,'.....                ......';lxOOOxddxkkxdoodOKKKKXNNK0xoc;;,;:coxkO00KXNNWWWMMMMMMMMMMMMMMMWWWWWWMMMWWX0Okkkxdllc:;,,,'........   ..................',cx0XXXXXNXXNNNNNNNNNWWWWWWNNNWWWWWWWNNNNXXXXXXKKOkdoooooooooooooooooooooolcccllloxkOOOkxxkOOkdollooooodddxxkO0KKKXXN\n" +
"ooooooooooooooooolllllllloooolc::;'.....                   ....;lk0KK000Okxdddkkxdx0NWWNKkdc;,,;clodxkO00KXNWWMMMMMMMMMMMMMMMWWWWWWMMWWNXK000Okdl:,''..'..............'',,;;;;;;,,,,;:cldOXNNNWWWWWNNNNXXKK00OOOOOOO0KXNWWMWWWWWNNNNXXXXKOxollooooddxxxxddolllodoolllllllodk0K0OOO0000OkxkOO00000KKKKKKK0OO0\n" +
"ooooooooooooooooooooooollloooolllc:;;,'.....                  ..,lxO0KXX0kkO0KXKOkOKWWWWWXOd:,,;:ldxkO0KKKXNWWMMMMMMMMMMMMMMMMMWWWWMMWWNNXXXKOxoc;'...''''.......'',;:lodxxkkkxxxxddxkOO0KXXNNNWWWWNXKkxdoc::;;;;:cldk0XXXNNNNNNNNNXXXNNXKOxolllloodxxxxxdooodxkkkxdddddooodkKXK0OO00KK0000000000000OOOkkkkk\n" +
"oooooooooooooooooooooooooolllooollllcc:;;,'...                ..,::::lxOKXXXNWWWNXNWWWWWWWKxc;,,:oxkO0KKKXXNWWWMMMMMMMMMMMMMMMMWWWWWWWWWNNXXKkdlc:,'.',,;,''',;:ccldkO0KKK00OOOOOO0OkkkkxdooddxkO0KXKko:;'.......,cokOOxdlloxkOOOkxxO0XXXXXK0kxxxddxxddodxxkO0XXXXXKK0OOkkxxk0XXXKKKKKKK0OOOOOOkkkOO00KKKKXX\n" +
"oooooooollllllloollooooooolllllollllllccc::;,'...             ..,'....,ckKXK00OOO0XWWWNNNNX0dl::cokO00KXXNNNWWWWWMMMMMMMMMMMMMWWWWWWWWWWNXK0Okdolc;,;:clllllodxOO00KXNXKOdlccccloollc;,'''.....',;cdxxdolc:;,,;:cdkOOxl;,'',:ldxxdooxkOOkO0KXXXXXKKK0kddxOKXNWWWWNNXXXXXXXXXKKXXNWWWWNNXXKKKKKKKXXXNNWWWWWWM\n" +
"ooooooolllllllloolloooolllllllllllllllllllcccc:;,'.....       ..'.  ..':dOOo:,'',:d0NWNXXNNNKOxddxOKXNNWWWWWMMWWWWMMMMMMMMMMMMWWWWMMWWNXKK0OOxdoollldkO0000KKKXNNNNXNXKko:'....',,'.......       ...;cdOKKK00OOO0K0Oxoc:ccccodxkOOkdoodddoooxO0KXNNNNXK0KXNNNNXXKK000KKKKKXNNNNNWMMMWWWWWWWWNNWWWWWMMMWWWWWW\n" +
"lllloooolllllllllllloollllllllllllloooollllllllcc::;,'....   .......';;coddc'.   .;xXWWWWWWWWXK0OO0KNWWMMMMMWWWWWWWMMMMMMMMMMMWWMMMMWWNXKK0OxdddxkO0KNNNNXXXXNNNNXKOkxxxoc;'........                .;d0KK0KKKKXNXKKKK0000Okkkkkkkxoc:clooc::codkOKXXKXXXXK0kdoodxkO000KKKXXNNNWWWWMMMWWWWWWWWWWWWWWWWWNNNWW\n" +
"llllooooooollllllllllllllllllllllllllollllllllllllllcc::;,'.......',;,''',cc:,....:xXWWWWWWMWNXXKKKXNWWMMMMMMWWWWWWMMMMMMMMMMMMWMMMWWWNXK0OOkkk0KXNNNNNNXKKKXNXK0Oxo:;::ccc;,''.'''............  . .'lxkdc::ldxkOO0KXNNNXKOkdooooooooollllc;,,;:cdOKK0000Okdc,...';cdk0XNNNNWNWWWWWWWWWWNWWWWWWNNXKK00000KKX\n" +
"llooooooooooolloooooooollllllllllcccllllllllllllllllllllcccc::;;;;;,'..  .,colc::ld0NWWNNNWWWWWWNNNNWWWMMMMMMMWWWWMMMMMMMMMMMMMMMMWWWNXK0000KKXNNWWWWNNNXXXNXK0kxdol:,'..',,;:ccclodollodxxxxolc:::cdOOxc,',;:clodxk0KK0OkkxxxdxxxxxkOOkxdl:,'',;lxOkxddxkdl;'.. ..':oOKNNWWWWWWWNNNNNNNNNWWWWNX0OkkxxxxkkOO\n" +
"oooooooooooooooooooooooolllllllllllllllllllllllllllcccllllllolloolc;,.....,lxOOxddk0NWNK0KXNWWWMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNNXKKKKXNNWWWWWWNNXXXNNNNX0kxdlc:;'......';codk0KKK0OkkkkkOKKKKKXXNX0kxxxxxxkkO00KKOxlcclodxkOOOOO0KXXK0xo:,,;coxxoooddl;,'......,:dOXWWWMWWWWWNNNNNNWWWWWWNXK0000000KKXX\n" +
"lloooooooooooooooooooooolllllllllllllllllllllllllllllllllllooooooolc:;;;;:cokOOOOkOKWWN0kk0XNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNXXXXXNWWWWWWWWNXKKKKXXKOkdolc:::;,,,'',;:cllodxdol:,'',:okKXNNNXXXXKKK000KXNNNXNNX0kdlccclodxkOOO0KXNNX0kxdddxkkkkxdl;'''',;::cldk0NWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWWW\n" +
"llllooooooooooooooooooollllllllllllllllllllllllllllllllllloollllllllllllllllodk0KXXNWWNKkkOKXNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNWWWWWWWWWWWNXXXXK0kdooodxxkkkxddoddddoolcc:,'.....';cdO0OkddooodxdoloxkO0O0OOO0000kxxxdollodxkOKXXNNNXXKKKXXXXKOdc;,,;:cok0XXNNWNNNNWWNNNNNNNNNNWWWWWWWWWWWWWWWWWWW\n" +
"llllllllllllllloooooooollllllllllllllllllllllllllllllllllllllllloolllllllllooodk0XWWMWNX0OO00XNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMWWWNWWWWWWWWWWWWWNNNXXNWWWNNXXK0OO0KXXXNXKKKXXXXXK0Okdoc;,'',:ldxxdc;'.....';:codxkkkkxo:;;:loxkO00OkdlllodkkO0KXNNNNWWWWWWNK0OkxdxOKXNWWWWWNNXXK00OkkkkO0KKXXNNXKKKXXNNNNNNNNX\n" +
"lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllollox0XWWWWNXK0000KXNWWWWWMMMWMMMMMMMWWWWMMWWWWWWWWWWNWWWWWWWWWNNXKKK000KXXXXKXNNWNNNNNXXXXNNNWWWNNNNNXKK0Odcclxkkdc'.      ..';cdkOOO0ko;.    ..';cdOK0kollloddxxxkOO0KXNNWWWWWNNNNNWWNXXXNXK0OOkxdddooooxkO000Okdollodxxkkkkxxd\n" +
"lllllllllllllllllllllllllllllllllllllllllllllllllllllccllllllllllllllllllloolodk0XWWWWXKOO0OkkkkOKNWWWWWWWWWNNWWNNXNNNNNNWWWWWWNXXXNNNNNNK0kdddxO0KKKKKKKXNNNXXXXXNNNXXNWWNXXKKXXXXNWNK00KKkl,.         ...',;:cdkko,.        .,lk00OkkkkOOOkxxdxxk0KXNWWWWWWWWWWWNX0Okdooooodddddddxxxxdol:;;,''''',,,,,,,,\n" +
"lllllllooooooooooooollllllllllllcllllllllllllllllllllllllllllllllllllcccclllodxOKNWNNXKkxxdoc;,,:dKNWWWWWWNNXXK000OkxxxkOKKXXXK0OO0XNNXK0kdc;;cdOKNWWNNNNWNX0kdddkkkkOO0XXXK000KXNWWWWNWWN0o,.            ......:dkd:.         ..;ldxxxdooodxkO00000KXXNNWWWWWWXXKOxl:,...',;:cccccc::;;,,''................\n" +
"llllloooooooooooooooolllllllllllllllllllllllllllllllllllllllllllllllcccclllloxOKXNX0OOkdllc:,'..;dKNWWWWWNNNX0kxkOOkoc:;:clodddooxOXNXKkdc:;;:dOKXNWWWWWNX0kdo:;;:cloxO0KK000O0KXNNWWWWWWNKkl,.           .... .;ldo:'........    ..........';cloxO0XNWNXXXKK0Odl:,...    .......................  ......   \n" +
"lllooooooooooooooooooollllllllllllllllllolllllllllllllllllllllllllcccllllllldk0XNN0doddl:;::cc:;cxKNWWWWWWNNX0kkkOOkdc;'''',;:clox0XXKOxl::lox0XNWWNNXK0kdlc::;;:ldkOOOkoc:cloxkKXNWWWWWWWWX0d:..     ...';;:;;,:llc:;;,,,,,,,''..            ..';okKNWNK0kxoc,..                    .. .                   \n" +
"ooooooooooooooooooooooooolllllllooooooooooooooooooolllllllllllllllllllllllloxOKNWNKkxdoc:cllllllldOXNWWWWWWNNXK0Okxol:;'....',:ldk0XK0kdodk0KKXNNNNX0xol:;,,,,;cdkOkdc;,...;ok0XNWWWWWWWWWNKOxo:'....,;cloddddooodolc:;;,'.....',,,....     ..,:cldk0XXX0ko:,.                                           ...\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllldk0XWWWNXKxc;:lol::::::okKNNNWNNNNNNXKkdollc::::::coxk0XNX0OkO0XNNNNWWWNKkdolccllllodxxoc,...';lkKXWWWWWWWWWWNNX0kxoc;;;:cloddxdddddddddolc:,,'...   ..',,'''....:oddxddxkOkxdo:'.                                        .......\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllloxOKXNWWWWKd::cc:,...'',cdO0000KKKXXNNNK0OO0O0000000KKXNNWWNNXNNWWWWWWNXOxollcccccllllc;'..,:lxOXNNNWWWWWWNX0Oxddlc:;,;codoodxxxdooooddoooooollcc;,....   ...',;coxkdlc;;:c:,...''..                          ....................\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllclldk0XNNWWNXkc;clc;'....':lolc::clodxOKNNNNNWWWWWWWWWWNNWWWWWWWWWNXK0KKXX0dc;,''..........';ldO0KXNNNNWWWNX0xoc;,,,''',;cloooddxxdollloooooooollllllcc:;;,......'codoc,'..  ..   ..''..                   ........................  \n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllldk0XNNWNKOo::cl:,......';,....'',,;lxOKXNNNNNNNNWWWWWWWWNNNNNNX0xlclok0K0kdc:;'..  ...;ldk0KKXXNNNNNNX0ko:,'...',;::clllloodxxdollllllllloolllllllllllllcc:::clll:'.            .....                      ..........             \n" +
"oooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllldk0XNNWNKkoc:;,'.. .......  ........,:lodxxxxkO0XNNWWWNK0OOxdddoc;,',;:ok0K0Oko:'..,:ok0KXXXNNWNNX0Oxl:,'...',;:clooollllodxxxdolloolllllllllllcllllooooodddxkkxo:,'.....        .....                                            \n" +
"oooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllldk0KXNWNKkdl:,.....         ...........'',,;;:lxOKXXXKkolc:,,,,,,,'''..',cdxxxoc:coxOKXNNNNWNXKOkdl:,......',:cloodooollodxxxddollllllloollllllllllloddddddxdddoollccc::;,'.............                                          \n" +
"oooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllldxOKXNWN0xoc;......        ..... .........',:cldkO0Oxoc;'.... ...'''''.....,,;:cdkKXNNNNNNXX0xl:,'.......',:clllloooooooodxxdoolllllllllllllllllllloddddoooolllllclllllllcc::;,,,'''',,'.                              .....'',,;:\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllloxO0XNNN0dlc;.             ..... .......';:coddddool:;,,....    ...'''....';:cok0KXNNNNXK0koc,'.........';cloolllllloloodddddollllollllllllllllloooddddddoolllcccccllllllllcccccccc:ccllc;,........................',,;;::::::ccll\n" +
"oooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllloxkOKXNNKxo:;.......       ............,;cccllc:;,,,,,,'..   .    ..',,,;coxxk0KKXNNNX0kdl:'..........',:clooolllllllooddddooolllllllllllllllloooodddddoollllllcclllllllllllccccclloodxkOkxolc:::;;;;;;;;;:::::cccccclllllllccclll\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllloodxO0XNNXOdc;'..,;ccc:;,..............';::;;,,''''.......         ..;codkO000KKXXNNX0xo:,'......... ..,:cllllllloooloooooooooollllllllllllllloooodddoollllclllllllllllllllllllcclloooodkO0Oxolcccccccccccclllllllllllllllllllllloo\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllloddxk0XNNX0dc,..';lxO00Oxc'.............'''..............        ...;oxO0KKKKKXNNXKOdc,...........  ..,:llllllllloooooollllllllllllllllllllclloddxddoolllllllllllllcllllllloollllooollloxkOOkxoccllllllllllllooollllllllllllllooodd\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllodddx0XNNKOd;.. ..,:ldkkxc,..''......  ...................     ..,:oxO00KKKKKKKK0koc,..  .   .  ....':clooollllllllllllllllllollllllllllllllllodddddooollllllllllllllllllllllllllllllllodxkOOkdololllllllllllooollllllllloooooddddd\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllooooxOXNX0Oo,.    ....,;,'.......',,..          .........   ..';ldxO0KKKKKKK0Okxl:,...  .       ...,:clooooolllllccllloollllllllllllllllllllooddddoooollllllllllllllllllllllllllllccllloodxOOkxddoolllllllllloolllllllloooooodddooo\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllloooodOXNX0kl,...   .    ...     .''...             .....  ..;coxOOO000KKKKOxlc:;'..  ...    ..  ..,cllllllllllllllclloooolllllllccllllooolloodddooooooolllllllllllllllllllllllllllccllloooxkOkxdoollcllooolloollllllllloooooooooool\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllooooox0KXX0x:.           ....    ...               .......,:oxkO0000KK0OOxdl:'......           ...;clollcllllloolllllloooollllllcccclloooolloddddolllooollllllcllllllooollllllllloollloooodkOOkxoolcccllooooooolloollcclloooddoooooo\n" +
"oooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllodddk0KXKOo,.           ...                      .....,:loxkOkO00KKKOxol;,'........           .':lllllllllllllllllllloooollcclllllllloollloodddollcllllllllllclllllloooollllllllllllllloodkOOkdollllllllloooooooolllcllloodddooolll\n" +
"oooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllcloddxOKXXKkl'.          ....              .........''';cdkOOOOO0K00Oxl:,'...                 ..':loolllllllllllllllllloooollclllllllllllllooooodoolllllllllllllllllllooooolllllllllllllloddxOOkdolllllccllooolloolllllllllooooolllll\n" +
"oooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllodxkOKXX0x:..         .....             ...........';cok0000KKK0Odl;'....                  ..,:clollllllllllllllllllllooollllllllllllllllooooooooolllllllllollllllllooooolllllllllllllloddxkkxdoolllllllloolllllllllloollllooolllll\n" +
"oooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllloodxkOKX0ko,..         ....             ............':dkO00KXKK0xl;..                     ..';:cclllllllllllllllllllllllllollloolllllllllloolllooooollllllloooollllloooooollllllllooollloodxkkkxdolllllllloolllllllllooollllllooolll\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllloooodxk0KKOd:'...       ....              ............,lxO0KKXKOxo:'.                      ..';clllllllllllllllllllllllllllloooooollllllllllooolooooolllloooooooooollloooooooolllllloolllllooxkkkkxdolooollooollllllllllollolllloooooo\n" +
"oooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllooodkOKXKOo;..         ....              .......''..,cokO0KXKOd:,..                      ..,:cloolllllllllllllllloolllllllooooooollllllllllooooooooolllooooooooooolllooooooooolllllooolllloodxxkkxdoooooolllllllllllllllllooooooooooo\n" +
"oooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllloodk0KKKOl,.....      ...             .........''.';oxkOKK0ko;..                 ..    .';clollllllllllllllllllloooollloooooooollllllloooloddddooollllloooooooooolllooooooooolllllooolllloooddxkkxdooooolllllllooolllllllloooooooool\n" +
"oooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllclodO0KKKkc'.';;,'........            .............'cxO00K0xl,..                      ..,:llollccclllllllllllllllooolllllloooooollllllloooodddoolllllooolooooooooolllooooooooollllooolllllooooodxkkxddolllllllllooooooooloooooooollll\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllllcllllc::ldOKXK0d:'.;oxkxol;'...             .............;ok0KKOxl;..   ...                ..,:llllcccclllllllllllllllllllllllllloooooolllllooooddoollllllooooooooooooooooooooooooooooooooollllllooooodxkkxdooollllllllooooooooooolllllllll\n" +
"ooooooooooooooooooooooooooooooooooooooooooooooooooooollllllllllccllolc:;;cdOXXKkc'..,okOOxo:'...     ...... .............,lx0KK0xl,..                      ..,:clllllllllllllllllllooooooooolllllllooooooooooooooooolcccllooooooooooooooooooooooooooooooollllllllloolloodkkkxdolllllllllooooooooooooolllllll\n" +
"oooooooooooooooooooooooooooooooooooooooooooooooollloollllclllllllllllc;;;cx0XXOo,...';ccc;,......  .':ool,.  ........ ..':dOKK0ko;..                      .':clllllllllllllllllllllllllloollllllllllooooooooooolllllllccclllllllllllooooooooooooooooooollllllllllooollloodxkxxddollllllloooooooooooollllllll\n" +
"oooooooooooooooooooooooooooooooooooooooooooooooolllollllccclllcclllc:;,';lx0XKx:........... .......,cdxdc,.....       ..;oOKXKOd:'.                      .,:lllllllllllllllllllllllllllllllllclllllloooooooooollllllllllllllllllllllloooooooooooooooooollllllllllloolllllodddxkxdolllllllllloooolllllllllooo\n" +
"ooooooooooooooooooooooooooooooooooooooooooolllllllllllllllccccllcccc;'.';lx0KOl'.....        ......,::;,..  ..        .,lkKXXKkl,.                      .,:cllllllllllllllllllllloooollllllllllllllloooooollllooooooooooooooooollllllloooooooooooooooolllllllllllllllllllllooxxxxdooolllllllllllllllllollooo\n" +
"oooooooooooooooooooooooooooooooooooooooollllllllllllllllllccclllccc:,..';lx00x;.             ..........         .......;d0XX0ko;..                    ..,cllcllllllllllllllllllllooooollllllllllllloooooolllllooollloooooooooooooooooolloooooooooooooollllllllllllllllllccllodxxxxxdoooooooooooloolllollllll\n" +
"ooooooooooooooooooooooooooooooooooooooollllllllllllllllllllccclllcc:,..';ok0Oo'.              ....            ........;oOKXKkl,.                     .,;cllllllllllllllllllllllllloollollllllllllllllooooooollllooooollllllllooooooooooooooooooooooooollllloolllllllllllclllloodxxxdddooooolllllllllllllllll\n" +
"ooooooooooooooooooooooooooooooooooooooollllllllllllllllllllccccllool;'.'cxOOd:.               ...             ......';oOKK0ko;.                     .,:cllcclllllllllllllllllllllloolloooooooooollllllloooooolllooooooollllllllooooooooooooooooooooooolllloollllllllllllllllllldxxxxdddooollllllloooollloooo\n" +
"ooooooooooooooooooooooooooooooooooooooollllllllllllcllllllcclcclloddc,';ok0kl,.                               ......;ok0KOxo;'.                    .':cclllccllllllllllllllllllllllllloooooooooooooooooooooooooloooooolloolllllooooooooooooooooooooooolllllllllllllllllllllllllodxxdddxddoollcllllllllllllll\n" +
"oooooooooooooooooooooooooooooooooooooollllllclllllccccllllllllllldxdc;,cx0Od;.            ....               ......;oOKKOxl;'.                     ':clllllllllllllllllllllllllllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllooododdxxxxdoolllllllllllllll\n" +
"oooooooooooooooooooooooooooooooooooooolloolllllllllccccclllllllloddo:,;lkOxc.            .....              .....';oOKK0xc,..                     .,clllooolllllllllllllllllllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllloooooooooooodxxxdddoollllloolllll\n" +
"oooooooooooooooooooooooooooooooooooooollooolllllllllllllllllllloddol,..;oxo;.                              .....';oOKKOxc,..                      .,clllooollcccclllllllllllllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollloooooooooooooooolllooooddddooolooooooooo\n" +
"ooooooooooooooooooooooooooooooooooooooloolllllllllllllllllllclodxdl;...':lc,.                             ......,lkKKOdc,..                      .';clollllccclllclllllllllllllllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolloolllooooodddddooooooooooo\n" +
"ooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllloddl:,....';,.                              ... .'lk000xc'..                       .,:llolllccllllllllllllllllllllllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollloooooooooooddddddddddddddd\n" +
"oooooooooooooooooooooooooollloooooooooooolllllllllllllllllooodxxdc;,'....'..                                  .ckKKOdc'...                       .':cllolllllllllllllllllllllllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooloooooooooolllooddddddddddd\n" +
"ooooooooooooooooooooooooollllloooooooooollllllllllllllllllodxkkkdc;;,.. ....                                 .:x0KOdc'...                        .';cllllllllllllllllllllllllllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooloooooolllllllllllllllooooooooodd\n" +
"ooooooooooooooooooolllloollllllllllllllllllllllllllllllllodkO00Oxc;,'.. ....                                 .;ldol;..             ..''...       ..;llllllllllllllllllllllllllllllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllcclloolllcllllloooo\n" +
"ooooooooooooooooooolllloolllllllllllllllllllllllllllllclldkO0KK0d:'...                                        ..'...          ....';ldxdc,.. .....':loollllllllllllllllllllllllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllcccllllllcclllllllll\n" +
"oooooooooooooooooollloooolllllllllllllllllllllllllllllllldkO0KK0d;..                                                           ...,lxO0Od:.......',:looollllllllllllllllllllllllllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllllll\n" +
"oooooooooooooooollllloooolllllllllllllllllllllllllllllllox0KKKK0d:..                                                              'lkKKOd:.......',;clolllllllllllllllllllllllllllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllloooollllloooolllllllllll\n" +
"ooooooooooooooooooooooooollllllllllllllccllllllllllllccldOKXXKK0d:..                                                             .,o0KKOd:'.........,cccloollllllllllllllllllllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooollllllloooooooolllllllll\n" +
"ooooooooooooooooooooooooollllllllllllllllccllllllllllccokKXXKK0Oo;.                                                              .;d000Od:'..      .':ccloolllllllllllllllllllllllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolooooooooollloooooo\n" +
"ooooooooooooooooooooooooollllllllllllllllllllllllllooookKXKKK0Oxl'.                                                             .'ck0KK0d:..     ..,coooolllllllllllllllllllllllllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolloooooollllooooooo\n" +
"oooooooooooooooooooooooolllllllllllllllccllllcclllloodk0XXKKK0Od:.                                                              .'cdO00Od:'......':lxxxxolllollllllllllllllllllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllooolloolllloooooo\n" +
"oooooooooooooooooooooooolllllllllllllllcllllllcllllldk0XX0O000Oo;.                                                               .;ldkOko:'.......,:looooloolllcclllllllllllcccllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooolllooooloooooooooooo\n" +
"oooooooooooooooooooooooolllllllllllllllllcclllcccllox0XN0OOO00kc.                                                               ..,cdkOxl,.     .....''',:cllllllllllllllllllclllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"ooooooooooooooooooooooooolllllllllllllllccllllllclodOXX0kxOKK0d;.                                                 ...... .      .':okO0kl,.             ..';clooolllllccllooollllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"ooooooooooooooooooooooooolllllllllllllllllllllllllxOKNXOxxOK0kl,.                                                 ......        .,lxO00Oo;..      .....    ..;coolcclccclloooolllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"oooooooooooooooollooooooollllllllllllllllllllllllok0KK0kkkO0Oxc.                                                                .'cx000Oxc'.      ..'''..    .';:ccllccllllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo\n" +
"oooooooooooooooolllloooolllllllllllcllllllllllllodkOkxddkO00Od:.                                                                 .:x0000kl,.       ..,,'..    ..,:cllclllllllllllllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo");
                break;
                
            }else {
                long fact = calcfact(num);
                System.out.println("The factorial of " + num + " is: " + fact);
                
                
            }
            
        }
    }
    
    private static long calcfact(int zxc) {
        long fact = 1;
        for (int i = 1; i <= zxc; i++) {
            fact *= i;
}
return fact;
    }
}

